package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate predicate;
    private DbIterator child1, child2;
    
    Tuple tuple1;
    
    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @author hrily
     * @param predicate
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate predicate, DbIterator child1, DbIterator child2) {
        this.predicate = predicate;
        this.child1 = child1;
        this.child2 = child2;
        this.tuple1 = null;
    }

    /**
     * @author hrily
     * @return The predicate used to join children
     */
    public JoinPredicate getJoinPredicate() {
        return predicate;
    }

    /**
     * @author hrily
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        TupleDesc td = child2.getTupleDesc();
        return td.getFieldName(predicate.getField1());
    }

    /**
     * @author hrily
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     */
    public String getJoinField2Name() {
        TupleDesc td = child2.getTupleDesc();
        return td.getFieldName(predicate.getField1());
    }

    /**
     * @author hrily
     * @return The Tuple desc of the join
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        TupleDesc td = TupleDesc.merge(child1.getTupleDesc(), 
                child2.getTupleDesc());
        int index = child1.getTupleDesc().numFields()
                + predicate.getField2();
        td.removeField(index);
        return td;
    }

    /**
     * Open iterators
     * 
     * @author hrily
     * @throws DbException
     * @throws NoSuchElementException
     * @throws TransactionAbortedException 
     */
    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        super.open();
        child1.open();
        child2.open();
    }

    /**
     * Close iterators
     * 
     * @author hrily
     */
    public void close() {
        child1.close();
        child2.close();
        super.close();
    }

    /**
     * Rewind the iterators
     * 
     * @author hrily
     * @throws DbException
     * @throws TransactionAbortedException 
     */
    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        child2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        if(!child1.hasNext())
            return null;
        if(tuple1 == null)
            tuple1 = child1.next();
        if(!child2.hasNext()){
            child2.rewind();
            tuple1 = child1.hasNext()
                    ? child1.next()
                    : null;
        }
        Tuple tuple2 = child2.next();
        while(  tuple1 != null &&
                tuple2 != null &&
                !predicate.filter(tuple1, tuple2) ) {
            if(!child2.hasNext()){
                child2.rewind();
                tuple1 = child1.hasNext()
                        ? child1.next()
                        : null;
            }
            tuple2 = child2.hasNext()
                    ? child2.next()
                    : null;
        }
        if(tuple1 == null || tuple2 == null)
            return null;
        Tuple tuple = Tuple.merge(tuple1, tuple2);
        /* 
         * Uncomment Following if required
         * Test cases doesn't remove duplicates
         */
        // int skipIndex = child1.getTupleDesc().numFields()
        //         + predicate.getField2();
        // tuple.removeField(skipIndex);
        return tuple;
    }

    /**
     * @author hrily
     * @return return the children DbIterators of this operator. If there is
     *         only one child, return an array of only one element. For join
     *         operators, the order of the children is not important. But they
     *         should be consistent among multiple calls.
     * */
    @Override
    public DbIterator[] getChildren() {
        DbIterator[] children = {child1, child2};
        return children;
    }

    /**
     * Set the children(child) of this operator. If the operator has only one
     * child, children[0] should be used. If the operator is a join, children[0]
     * and children[1] should be used.
     * 
     * @author hrily
     * @param children
     *            the DbIterators which are to be set as the children(child) of
     *            this operator
     * */
    @Override
    public void setChildren(DbIterator[] children) {
        child1 = children[0];
        child2 = children[1];
    }

}
